# -*- coding: utf-8 -*-
"""hw5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y4Y0GVDG88jPmeAVyoytLrAeYNhbmt5x
"""

# -*- coding: utf-8 -*-


from airflow import DAG
from airflow.models import Variable
from airflow.decorators import task
from datetime import datetime
import snowflake.connector
import requests

def return_snowflake_conn():
    conn = snowflake.connector.connect(
        user=Variable.get('snowflake_userid'),
        password=Variable.get('snowflake_password'),
        account=Variable.get('snowflake_account'),
        warehouse='compute_wh',
        database='hw5'
    )
    return conn.cursor()

@task
def extract():
    # Retrieve API key and URL template from Airflow Variables
    api_key = Variable.get('vantage_api_key')
    url_template = Variable.get("vantage_api_url")

    # Define the symbol
    symbol = 'GOOG'
    url = url_template.format(symbol=symbol, vantage_api_key=api_key)

    response = requests.get(url)
    data = response.json()

    return data


@task
def transform(data):
    transformed_results = []
    if 'Time Series (Daily)' in data:
        for date, values in data['Time Series (Daily)'].items():
            transformed = {
                'date': date,
                'open': values['1. open'],
                'high': values['2. high'],
                'low': values['3. low'],
                'close': values['4. close'],
                'volume': values['5. volume']
            }
            transformed_results.append(transformed)
    return transformed_results

@task
def load(transformed_data):
    # Use the same symbol as in the extract function
    symbol = 'GOOG'
    target_table = "hw5.cat1.stock_price"

    if not transformed_data:
        print("No data to load.")
        return

    try:

        cur = return_snowflake_conn()


        cur.execute("BEGIN;")

        # Create or replace the target table in Snowflake
        cur.execute(f"""
        CREATE OR REPLACE TABLE {target_table} (
          date DATE,
          open NUMBER,
          high NUMBER,
          low NUMBER,
          close NUMBER,
          volume NUMBER,
          symbol VARCHAR
        )
        """)

        # SQL statement to insert data into the table
        insert_sql = f"""
        INSERT INTO {target_table} (date, open, high, low, close, volume, symbol)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        """


        for record in transformed_data:
            cur.execute(insert_sql, (
                record['date'],
                record['open'],
                record['high'],
                record['low'],
                record['close'],
                record['volume'],
                symbol
            ))

        cur.execute("COMMIT;")
        print("Data loaded successfully.")

    except Exception as e:

        cur.execute("ROLLBACK;")
        print("An error occurred while loading data:", str(e))
        raise e
    finally:
        cur.close()

# Define the DAG
with DAG(
    dag_id='Airflow_dag',
    start_date=datetime(2024, 10, 10),
    catchup=False,
    tags=['ETL'],
    schedule='30 6 * * *'
) as dag:


    extracted_data = extract()
    transformed_data = transform(extracted_data)
    load(transformed_data)